security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      stateless: false
      custom_authenticator: App\Security\LoginAuthenticator # Usamos solo el LoginAuthenticator personalizado

      # Eliminar form_login porque estás usando un autenticador personalizado
      # form_login:
      #   login_path: login
      #   check_path: login
      #   default_target_path: homepage # Redirige a la página principal después de login

      logout:
        path: /logout
        target: homepage # Redirige a la página principal después de logout

      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800
        path: /

  access_control:
    - { path: ^/empresa/c, roles: PUBLIC_ACCESS }
    - { path: ^/empresa, roles: ROLE_EMPRESA }
    - { path: ^/postulante, roles: PUBLIC_ACCESS }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/logout, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: PUBLIC_ACCESS }
