controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

redirect_after_login:
  path: /redirect
  controller: App\Controller\SecurityController::redirectAfterLogin

postulante_registro:
  path: /postulante/registro
  controller: App\Controller\PostulanteController::registro

empresa_dashboard:
  path: /empresa_c/empresa
  controller: App\Controller\EmpresaCController::dashboard

homepage:
  path: /
  controller: App\Controller\HomeController::index

publicar_oferta:
  path: /publicar-oferta
  controller: App\Controller\OfertaLaboralController::publicarOferta
  methods: POST

eliminar_oferta:
  path: /eliminar-oferta/{id}
  controller: App\Controller\OfertaLaboralController::eliminarOferta
  methods: DELETE

postulante:
  path: /postulante/{id}
  controller: App\Controller\PostulanteController::index
  methods: [GET]
