# config/services.yaml
services:
  # Default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # Makes classes in src/ available to be used as services
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Service for FileUploader
  App\Service\FileUploader:
    arguments:
      $targetDirectory: "%foto_perfil_directory%"

parameters:
  foto_perfil_directory: "%kernel.project_dir%/public/uploads/foto_perfil"
  profile_directory: "%kernel.project_dir%/public/uploads/profile"

  curriculum_directory: "%kernel.project_dir%/public/uploads/curriculums"
